### ISSUE TITLE
`TypeError - expected string or bytes-like object` raised when updating a subtask

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#195]
Related with https://talkback.golem.network/sentry/concent/issues/29/

Error message: `TypeError - expected string or bytes-like object`.

Reason:
Updating subtask fails on validation.

Solution:
Analyze the stack trace and find what field is causing this. Fix by adding extra validation.

### Traceback
``` python
TypeError: expected string or bytes-like object
  File "django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "utils/api_view.py", line 75, in wrapper
    response_from_view = view(request, message, *args, **kwargs)
  File "django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "core/views.py", line 64, in send
    return handle_send_force_subtask_results(request, client_message)
  File "core/views.py", line 421, in handle_send_force_subtask_results
    task_to_compute             = client_message.ack_report_computed_task.task_to_compute,
  File "core/views.py", line 1212, in store_or_update_subtask
    subtask_results_rejected        = subtask_results_rejected,
  File "core/views.py", line 1122, in update_subtask
    subtask.full_clean()
  File "django/db/models/base.py", line 1228, in full_clean
    self.clean_fields(exclude=exclude)
  File "django/db/models/base.py", line 1270, in clean_fields
    setattr(self, f.attname, f.clean(raw_value, self))
  File "django/db/models/fields/__init__.py", line 605, in clean
    value = self.to_python(value)
  File "django/db/models/fields/__init__.py", line 1399, in to_python
    parsed = parse_datetime(value)
  File "django/utils/dateparse.py", line 94, in parse_datetime
    match = datetime_re.match(value)
```

**Comment by rwrzesien** [comment]
After investigation I am closing this one as it:
1. was never reproducible because of unknown data which caused this.
2. didn't appear again in over a month.

Probably was caused by buggy validation, which was fixed along the way.

**Comment by cameel** [comment]
It happened again 12 days ago on the testnet: https://talkback.golem.network/sentry/concent/issues/27178/

I'm reopening this. The problem clearly persists.

**Comment by cameel** [comment]
This is still happening.

@PaweuB We need to give it a higher priority.

**Comment by pawelkisielewicz** [comment]
This problem happens, when a client sends request and in some time sends another request regarding the same subtask. There is a bug in our function `update_subtask`. It requirers `next_deadline: Optional[int] = None`, but during validation fields in `subtask.full_clean()` it should be datetime instead of int

**Comment by cameel** [comment]
@rwrzesien Sure but let's make a separate issue for those tests. The bug here should be fixed and merged without waiting for that big integration test.

**Comment by rwrzesien** [comment]
@cameel Right, added https://github.com/golemfactory/concent/issues/730.

**Comment by PaweuB** [comment]
Pivotal again:
https://www.pivotaltracker.com/story/show/159822787
